version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-bfd-multihop-node-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-bfd-multihop-node-policy/actions/workflows/test.yml)

  *This module is no longer maintained as it has been integrated into the [nac-aci](https://github.com/netascode/terraform-aci-nac-aci) module.*

  # Terraform ACI BFD Multihop Node Policy Module

  Description

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `BFD Multihop` » `Node Policies`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
